DB:
  DSN: host=localhost port=5432 user=postgres password=postgres dbname=pg-contest sslmode=disable

LogLevel: debug

ListenPort: 8083

ApiURL: https://dev.api-parviz.com/api/

PublicPrivKey: private_key_sec

AdminPrivKey: private_key_sec